name: Run Postman Demo

on:
  push:
    branches: [ main ]

jobs:
  run-newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install newman
        run: npm install -g newman

      - name: Run Postman collection
        run: |
          newman run demo.postman_collection.json \
            -e demo.postman_environment.json \
            --insecure \
            --reporters cli,junit \
            --reporter-junit-export results.xml

      - name: Upload results.xml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: postman-results
          path: results.xml
